language: python
sudo: required
services:
  - docker
cache: pip
env:
  - MIN_SCORE=9
os:
  - linux
python:
  - "3.6"
before_install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv install ./users
  - ./lintstats.sh
  - WITH_INTEGRATION=1 pipenv run pytest --cov=accounts --cov=users/arxiv --cov=registry --cov=authenticator --cov-report=term-missing accounts users/arxiv registry authenticator
after_success:
  - coveralls
