language: python
sudo: required
services:
  - docker
cache: pip
env:
  - MIN_SCORE=9
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pip install -r requirements/test.txt
  - ./lintstats.sh
  - ./tests/docker_tests.sh
  - nose2
after_success:
  - coveralls
