language: python
sudo: required
services:
  - docker
cache: pip
env:
  - MIN_SCORE=9
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install ./users
  - ./lintstats.sh
  - WITH_INTEGRATION=1 pipenv run pytest --cov=accounts --cov=users/arxiv --cov=authenticator --cover=registry --cov-report=term-missing accounts users/arxiv authenticator registry
after_success:
  - coveralls
