apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounts
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    service-group: "{{ .Values.labels.service_group }}"
