apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: accounts-ingress
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: accounts-ingress
    service-group: api
    env: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
    ingress.kubernetes.io/auth-url: "{{ .Values.auth.url }}"
    ingress.kubernetes.io/auth-signin: "{{ .Values.auth.signin }}"
    ingress.kubernetes.io/auth-response-headers: "{{ .Values.auth.response_headers }}"
spec:
  tls:
  - secretName: "{{ .Values.tls.secretName }}"
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "{{ default "/user" .Values.ingress.path }}"
        backend:
          service.name: arxiv-accounts
          servicePort: 80
