apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
    service-group: api
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ default 3 .Values.replicas }}
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
        service-group: api
        log-style: uwsgi
        env: "{{ .Values.namespace }}"
      namespace: "{{ .Values.namespace }}"
      # annotations:
      #   prometheus.io/scrape: 'true'
    spec:
      # This should keep the pods from clustering together on the same node.
      affinity:
        podAntiAffinity:
          # Multiple consul pods should not be placed on the same node.
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: container
                operator: In
                values:
                - "authenticator"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
        image: arxiv/authenticator:{{ .Values.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: LOGLEVEL
          value: "{{ default "40" .Values.loglevel }}"
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.secrets.jwt.name }}"
              key: "{{ .Values.secrets.jwt.key }}"
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
