apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
    service-group: api
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ default 3 .Values.replicas }}
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
        service-group: api
        log-style: uwsgi
        env: "{{ .Values.namespace }}"
      namespace: "{{ .Values.namespace }}"
      # annotations:
      #   prometheus.io/scrape: 'true'
    spec:
      serviceAccount: authenticator
      volumes:
      - name: vault-certificate
        secret:
          secretName: vault-certificate
      - name: vault-token
        emptyDir: {}

      # This should keep the pods from clustering together on the same node.
      affinity:
        podAntiAffinity:
          # Multiple consul pods should not be placed on the same node.
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: container
                operator: In
                values:
                - "authenticator"
            topologyKey: kubernetes.io/hostname
      containers:
      - name: "{{ default "arxiv-authenticator" .Values.deployment.name }}"
        image: arxiv/authenticator:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        env:
        - name: LOGLEVEL
          value: "{{ default "40" .Values.loglevel }}"
        - name: REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: REDIS_CLUSTER
          value: "{{ .Values.redis.cluster }}"

        - name: VAULT_ENABLED
          value: "1"
        - name: VAULT_HOST
          value: "{{ .Values.vault.host }}"
        - name: VAULT_PORT
          value: "{{ .Values.vault.port }}"
        - name: VAULT_CERT
          value: /etc/vault-certificate/vaulttls.cert.pem
        - name: VAULT_ROLE
          value: "{{ .Values.vault.role }}-{{ .Values.namespace }}"
        - name: KUBE_TOKEN
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        volumeMounts:
        - name: vault-certificate
          mountPath: /etc/vault-certificate
          readOnly: true
        - name: vault-token
          mountPath: /etc/vault

        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: "/auth"
            port: 8000
