namespace: development
loglevel: "40"
service:
  name: registry
deployment:
  name: registry
  
image:
  tag: "0.4.1-rc1"

labels:
  subsystem: api-gateway

redis:
  host: localhost
  port: 6379
  cluster: 0

ingress:
  host: api.arxiv.org
  path: "/api"
  name: registry

authenticator: authenticator

vault:
  role: registry
  host: localhost
  port: 8200

database:
  host: localhost
  port: 3306
  engine: mysql+mysqldb
  name: registry
