kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{ default "registry" .Values.service.name }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "registry" .Values.deployment.name }}"
    service-group: api
    log-style: uwsgi
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "registry" .Values.deployment.name }}"
