apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ default "registry" .Values.ingress.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "registry" .Values.deployment.name }}"
    service-group: api
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
    ingress.kubernetes.io/auth-url: http://{{ .Values.authenticator }}.{{ .Values.namespace }}.svc.cluster.local/auth
    ingress.kubernetes.io/auth-signin: https://api.arxiv.org/user/login
    ingress.kubernetes.io/auth-response-headers: Authorization
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:  # This will use the default certificate for the ingress controller.
  - hosts:
    - "{{ .Values.ingress.host }}"
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "{{ default "/api" .Values.ingress.path }}"
        backend:
          serviceName: "{{ default "registry" .Values.service.name }}"
          servicePort: 80
