name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITH_INTEGRATION: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install arxiv-auth dependencies
        working-directory: ./arxiv-auth
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test arxiv-auth
        working-directory: ./arxiv-auth
        run:  poetry run pytest --cov=arxiv-auth --cov-report=term-missing arxiv-auth
      - name: Install accounts dependencies
        working-directory: ./accounts
        run: poetry install
      - name: Test accounts
        working-directory: ./accounts
        run:  poetry run pytest --cov=accounts --cov-report=term-missing accounts
      - name: linter
        run: |
          pip install pylint
          ./tests/lint.sh arxiv-auth accounts
      - name: style check
        run: |
          pip install pydocstyle
          ./tests/style.sh arxiv-auth/arxiv_auth accounts/accounts


